### ISSUE TITLE
"bco_spec_version" as a URL?

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Specification#7]
Should the ["bco_spec_version"](https://github.com/biocompute-objects/BCO_Specification/blob/master/top-level.md#204-bco-version-bco_spec_version) field be expressed as a URL to the _RELEASE_ of the version used to draft it? For example: 
```json
"bco_spec_version": "v1.1-draft1" 
```
Becomes:
```json
"bco_spec_version": "https://github.com/biocompute-objects/BCO_Specification/releases/tag/v1.2"
```

**Comment by stain** [comment]
Yes, that is a very good idea, but it should be a permalink (e.g. using http://w3id.org/) rather than straight onto GitHub as those URLs are fragile.

Here's how we did this for CWLProv profiles:  https://w3id.org/cwl/prov/0.6.0

We use [semantic versioning](https://github.com/common-workflow-language/cwlprov/tree/0.6.0#versions) where we document in advance what we think is a major.minor.patch level 'change'.

How we declare it inside the Research Object manifest JSON:

```json
 "conformsTo": "https://w3id.org/cwl/prov/0.6.0",
```

(that is `conformsTo` from Dublin Core Terms)

**Comment by HadleyKing** [comment]
@stain 
This seems like a great idea but I am not sure I did it correctly.  
Can you check it out? 

[w3id.org/biocompute/spec/v1.2](https://w3id.org/biocompute/spec/v1.2)

**Comment by HadleyKing** [comment]
@kee007ney

**Comment by HadleyKing** [comment]
@stain 
Maybe this is in the documentation and I did not see it but what is to prevent from someone issuing a commit that has a malicious redirect?
